onboarding = false

[ui.toast]
delivery = "herdr"

[ui]
show_agent_labels_on_pane_borders = true

agent_panel_sort = "spaces"

[theme]
name = "terminal"

[[keys.command]]
key = "prefix+shift+g"
type = "popup"
command = "lazygit"
description = "run lazygit"
width = "80%"
height = "80%"

[[keys.command]]
key = "prefix+f"
type = "plugin_action"
command = "herdr-file-viewer.open-file-viewer"
description = "open file viewer"

[[keys.command]]
key = "prefix+w"
type = "plugin_action"
command = "worktrunk.open"
description = "worktrunk picker"